--- # Playbook to spin up CentOS Atomic Host instances and run a Bitcoin Core container
- hosts: localhost
  connection: local
  gather_facts: false
  remote_user: centos
  pre_tasks:
   - include_vars: vars/ec2.yml
  roles:
  - ec2instance

- hosts: "{{ ec2_tag_Type }}"
  remote_user: centos
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars_files: 
  - vars/ec2.yml
  tasks:
#  pre_tasks:
#   - include_vars: vars/ec2.yml
  roles:
  - mybitcoind
