--- # roles/ec2instance/tasks/main.yml
 - name: Launch Atomic Host instances
   ec2:
     instance_type: "{{ ins_type }}"
     region: "{{ ec2_region }}"
     image: "{{ ec2_image }}"
     key_name: "{{ ec2_keypair }}"
     group: "{{ ec2_secgroup }}"
     vpc_subnet_id: "{{ ec2_subnet }}"
     instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}"}'
     count: "{{ ins_count }}"
     wait: true
     assign_public_ip: yes
   register: ec2

 - debug: var=item
   with_items: "{{ ec2.instances }}"

 - add_host: name={{ item.public_ip }} >
             groups={{ec2_tag_Type}}
             ec2_region={{ec2_region}} 
             ec2_tag_Name={{ec2_tag_Name}}
             ec2_tag_Type={{ec2_tag_Type}}
             ec2_ip_address={{item.public_ip}}
   with_items: "{{ ec2.instances }}"

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.public_ip}} port=22 delay=60 timeout=600 state=started
   with_items: "{{ ec2.instances }}"
